export const DEFAULT_PROFILE = {
  key: 'main',
  profile: {
    displayName: 'Whiskey',
    username: 'whiskey',
    bio: 'Lost somewhere between code and chaos. Explorer of the digital abyss.',
    location: 'Vietnam',
    quote: 'Silence speaks volumes in the void.',
    avatar: '',
    background: '',
    music: '',
    status: 'online',
    viewCount: 0,
  },
  social: {
    discord: '',
    tiktok: '',
    facebook: '',
    github: '',
    youtube: '',
    instagram: '',
    spotify: '',
  },
  botInvite: '',
  bot: {
    description: '',
    features: [],
  },
  botGallery: [],
  bank: {
    bankName: '',
    accountNumber: '',
    accountName: '',
    qrCode: '',
    transferContent: 'donate',
  },
  theme: {
    primaryColor: '#8b5cf6',
    accentColor: '#38bdf8',
    glowIntensity: 50,
    blurIntensity: 70,
    particleCount: 80,
    particleSpeed: 30,
    cardRadius: 16,
    cardOpacity: 80,
    avatarSize: 120,
    avatarBorderWidth: 2,
    avatarGlow: 50,
    backgroundBlur: 0,
    backgroundBrightness: 100,
    backgroundScale: 100,
    profileCardWidth: 420,
    profileCardPadding: 32,
    buttonRadius: 12,
    buttonGlow: 40,
    musicPlayerSize: 'normal',
    fontFamily: 'Inter',
  },
  effects: {
    enableParticles: true,
    enableGlow: true,
    enableNoiseOverlay: true,
    enableGradientBorder: true,
    enableFloatingAnimation: true,
    enableMusicPlayer: true,
    enableViewCounter: true,
  },
  performance: {
    mode: 'auto',
    reduceMotion: false,
    mobileParticleLimit: 30,
    maxBlur: 80,
    maxGlow: 80,
    enableHeavyAnimations: true,
  },
}
