import mongoose from 'mongoose'

const ProfileSchema = new mongoose.Schema({
  key: { type: String, default: 'main', unique: true },
  profile: {
    displayName: { type: String, required: true },
    username: { type: String, required: true },
    bio: { type: String, maxlength: 300 },
    location: { type: String },
    quote: { type: String, maxlength: 200 },
    avatar: { type: String },
    background: { type: String },
    music: { type: String },
    musicTitle: { type: String, default: '' },
    musicArtist: { type: String, default: '' },
    musicCover: { type: String, default: '' },
    status: { type: String, default: 'online' },
    viewCount: { type: Number, default: 0 },
  },
  social: {
    discord: { type: String, default: '' },
    tiktok: { type: String, default: '' },
    facebook: { type: String, default: '' },
    github: { type: String, default: '' },
    youtube: { type: String, default: '' },
    instagram: { type: String, default: '' },
    spotify: { type: String, default: '' },
  },
  botInvite: { type: String, default: '' },
  bot: {
    description: { type: String, default: '' },
    features: [{ type: String }],
  },
  botGallery: [{
    url: { type: String, required: true },
    type: { type: String, enum: ['image', 'video'], default: 'image' },
    caption: { type: String, default: '' },
    enabled: { type: Boolean, default: true },
  }],
  bank: {
    bankName: { type: String, default: '' },
    accountNumber: { type: String, default: '' },
    accountName: { type: String, default: '' },
    qrCode: { type: String, default: '' },
    transferContent: { type: String, default: 'donate' },
  },
  theme: {
    primaryColor: { type: String, default: '#8b5cf6' },
    accentColor: { type: String, default: '#38bdf8' },
    glowIntensity: { type: Number, default: 50, min: 0, max: 100 },
    blurIntensity: { type: Number, default: 70, min: 0, max: 100 },
    particleCount: { type: Number, default: 80, min: 0, max: 150 },
    particleSpeed: { type: Number, default: 30 },
    cardRadius: { type: Number, default: 16 },
    cardOpacity: { type: Number, default: 80 },
    avatarSize: { type: Number, default: 120 },
    avatarBorderWidth: { type: Number, default: 2 },
    avatarGlow: { type: Number, default: 50 },
    backgroundBlur: { type: Number, default: 0 },
    backgroundBrightness: { type: Number, default: 100 },
    backgroundScale: { type: Number, default: 100 },
    profileCardWidth: { type: Number, default: 420 },
    profileCardPadding: { type: Number, default: 32 },
    buttonRadius: { type: Number, default: 12 },
    buttonGlow: { type: Number, default: 40 },
    musicPlayerSize: { type: String, default: 'normal' },
    fontFamily: { type: String, default: 'Inter' },
  },
  effects: {
    enableParticles: { type: Boolean, default: true },
    enableGlow: { type: Boolean, default: true },
    enableNoiseOverlay: { type: Boolean, default: true },
    enableGradientBorder: { type: Boolean, default: true },
    enableFloatingAnimation: { type: Boolean, default: true },
    enableMusicPlayer: { type: Boolean, default: true },
    enableViewCounter: { type: Boolean, default: true },
  },
  performance: {
    mode: { type: String, default: 'auto', enum: ['auto', 'high', 'balanced', 'low'] },
    reduceMotion: { type: Boolean, default: false },
    mobileParticleLimit: { type: Number, default: 30, min: 0, max: 50 },
    maxBlur: { type: Number, default: 80 },
    maxGlow: { type: Number, default: 80 },
    enableHeavyAnimations: { type: Boolean, default: true },
  },
}, { timestamps: true })

export default mongoose.models.Profile || mongoose.model('Profile', ProfileSchema)
